### ISSUE TITLE
An error in the installation of SDPB

### ISSUE THREAD

**Issue by einefrage** [yujitach/homebrew-tap#2]
Hi,
   I try to install SDPB today and I got an error report like this
In file included from /usr/local/Cellar/llvm/7.0.0_1/include/c++/v1/cstring:61:
/usr/local/Cellar/llvm/7.0.0_1/include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
In file included from src/BlockDiagonalMatrix.cpp:9:
In file included from /usr/local/Cellar/llvm/7.0.0_1/include/c++/v1/algorithm:642:
In file included from /usr/local/Cellar/llvm/7.0.0_1/include/c++/v1/cstring:61:
/usr/local/Cellar/llvm/7.0.0_1/include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>

Does any one know how to solve this problem?
Thanks in advance.

**Comment by yujitach** [comment]
Did you install Xcode and the associated command-line tools? That's a common pitfall.

**Comment by einefrage** [comment]
I installed Xcode 10.1. Can you tell me what are the other associated command-line tools.
It says lack of string.h. `what is that and where can I find it?

**Comment by yujitach** [comment]
Open Xcode's Preferences (⌘,) , select the Location tab. Then it can be installed. string.h should come with it.

**Comment by einefrage** [comment]
This is the location tab of Xcode, which should I click on

**Comment by einefrage** [comment]
I entered location tap in the preferences. Then I don’t know what to do with it.  It seems like Xcode is installed. How can I tell it is installed properly or not.

**Comment by yujitach** [comment]
Hmm. How about running `xcode-select --install` from the terminal?

**Comment by einefrage** [comment]
It says xcode-select: error: command line tools are already installed, use "Software Update" to install updates

**Comment by yujitach** [comment]
I finally understood the problem. Things changed in Mojave, see https://apple.stackexchange.com/questions/337940/ . 

The solution: run

    sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /


from the command line to install the header files. 

I am pretty sure that many packages in brew are bitten by this change... Hopefully it will be updated soon, to run this command automatically.

**Comment by einefrage** [comment]
Thanks. This time I did not receive error report.
