### ISSUE TITLE
A problem on my mac

### ISSUE THREAD

**Issue by Ha-oyzhang** [yujitach/homebrew-tap#3]
I'm trying to install sdpb on my mac.
But after I type in " brew install sdpb"
I get 

Last 15 lines from /Users/Wayne/Library/Logs/Homebrew/sdpb/01.make:
/usr/local/opt/llvm/bin/clang -I/usr/local/opt/llvm/include -g -O2 -Wall -ansi -std=c++0x -Isrc/mpack -I/usr/local/include -I/usr/local/include/boost -fopenmp -D___MPACK_BUILD_WITH_GMP___ -MMD -c -o obj/mpack/Rsyrk.o src/mpack/Rsyrk.cpp
/usr/local/opt/llvm/bin/clang -I/usr/local/opt/llvm/include -g -O2 -Wall -ansi -std=c++0x -Isrc/mpack -I/usr/local/include -I/usr/local/include/boost -fopenmp -D___MPACK_BUILD_WITH_GMP___ -MMD -c -o obj/mpack/Rsytd2.o src/mpack/Rsytd2.cpp
/usr/local/opt/llvm/bin/clang -I/usr/local/opt/llvm/include -g -O2 -Wall -ansi -std=c++0x -Isrc/mpack -I/usr/local/include -I/usr/local/include/boost -fopenmp -D___MPACK_BUILD_WITH_GMP___ -MMD -c -o obj/mpack/Rsytrd.o src/mpack/Rsytrd.cpp
/usr/local/opt/llvm/bin/clang -I/usr/local/opt/llvm/include -g -O2 -Wall -ansi -std=c++0x -Isrc/mpack -I/usr/local/include -I/usr/local/include/boost -fopenmp -D___MPACK_BUILD_WITH_GMP___ -MMD -c -o obj/mpack/Rtrmm.o src/mpack/Rtrmm.cpp
/usr/local/opt/llvm/bin/clang -I/usr/local/opt/llvm/include -g -O2 -Wall -ansi -std=c++0x -Isrc/mpack -I/usr/local/include -I/usr/local/include/boost -fopenmp -D___MPACK_BUILD_WITH_GMP___ -MMD -c -o obj/mpack/Rtrmv.o src/mpack/Rtrmv.cpp
/usr/local/opt/llvm/bin/clang -I/usr/local/opt/llvm/include -g -O2 -Wall -ansi -std=c++0x -Isrc/mpack -I/usr/local/include -I/usr/local/include/boost -fopenmp -D___MPACK_BUILD_WITH_GMP___ -MMD -c -o obj/mpack/Rtrsm.o src/mpack/Rtrsm.cpp
/usr/local/opt/llvm/bin/clang -I/usr/local/opt/llvm/include -g -O2 -Wall -ansi -std=c++0x -Isrc/mpack -I/usr/local/include -I/usr/local/include/boost -fopenmp -D___MPACK_BUILD_WITH_GMP___ -MMD -c -o obj/mpack/Rtrsv.o src/mpack/Rtrsv.cpp
/usr/local/opt/llvm/bin/clang -I/usr/local/opt/llvm/include -g -O2 -Wall -ansi -std=c++0x -Isrc/mpack -I/usr/local/include -I/usr/local/include/boost -fopenmp -D___MPACK_BUILD_WITH_GMP___ -MMD -c -o obj/mpack/iMlaenv.o src/mpack/iMlaenv.cpp
/usr/local/opt/llvm/bin/clang -I/usr/local/opt/llvm/include -g -O2 -Wall -ansi -std=c++0x -Isrc/mpack -I/usr/local/include -I/usr/local/include/boost -fopenmp -D___MPACK_BUILD_WITH_GMP___ -MMD -c -o obj/mpack/iRamax.o src/mpack/iRamax.cpp
/usr/local/opt/llvm/bin/clang -I/usr/local/opt/llvm/include -g -O2 -Wall -ansi -std=c++0x -Isrc/mpack -I/usr/local/include -I/usr/local/include/boost -fopenmp -D___MPACK_BUILD_WITH_GMP___ -MMD -c -o obj/tinyxml2/tinyxml2.o src/tinyxml2/tinyxml2.cpp
/usr/local/opt/llvm/bin/clang -I/usr/local/opt/llvm/include -g -O2 -Wall -ansi -std=c++0x -Isrc/mpack -I/usr/local/include -I/usr/local/include/boost -fopenmp -D___MPACK_BUILD_WITH_GMP___ -MMD  -o sdpb obj/BlockDiagonalMatrix.o obj/Matrix.o obj/SDP.o obj/SDPSolver.o obj/SDPSolverIO.o obj/main.o obj/parse.o obj/mpack/Mlsame.o obj/mpack/Mxerbla.o obj/mpack/Raxpy.o obj/mpack/Rcopy.o obj/mpack/Rdot.o obj/mpack/Rgemm.o obj/mpack/RgemmParallel.o obj/mpack/Rgemv.o obj/mpack/Rger.o obj/mpack/Rgetf2.o obj/mpack/Rgetrf.o obj/mpack/Rgetrs.o obj/mpack/Rlae2.o obj/mpack/Rlaev2.o obj/mpack/Rlamch.o obj/mpack/Rlanst.o obj/mpack/Rlansy.o obj/mpack/Rlapy2.o obj/mpack/Rlarf.o obj/mpack/Rlarfb.o obj/mpack/Rlarfg.o obj/mpack/Rlarft.o obj/mpack/Rlartg.o obj/mpack/Rlascl.o obj/mpack/Rlaset.o obj/mpack/Rlasr.o obj/mpack/Rlasrt.o obj/mpack/Rlassq.o obj/mpack/Rlaswp.o obj/mpack/Rlatrd.o obj/mpack/Rnrm2.o obj/mpack/Rorg2l.o obj/mpack/Rorg2r.o obj/mpack/Rorgql.o obj/mpack/Rorgqr.o obj/mpack/Rorgtr.o obj/mpack/Rpotf2.o obj/mpack/Rpotf2Stabilized.o obj/mpack/Rpotrf.o obj/mpack/RpotrfStabilized.o obj/mpack/Rrot.o obj/mpack/Rrotg.o obj/mpack/Rscal.o obj/mpack/Rsteqr.o obj/mpack/Rsterf.o obj/mpack/Rswap.o obj/mpack/Rsyev.o obj/mpack/Rsymv.o obj/mpack/Rsyr2.o obj/mpack/Rsyr2k.o obj/mpack/Rsyrk.o obj/mpack/Rsytd2.o obj/mpack/Rsytrd.o obj/mpack/Rtrmm.o obj/mpack/Rtrmv.o obj/mpack/Rtrsm.o obj/mpack/Rtrsv.o obj/mpack/iMlaenv.o obj/mpack/iRamax.o obj/tinyxml2/tinyxml2.o -L/usr/local/opt/llvm/lib -liomp5 -lgmpxx -lgmp -lboost_serialization -lboost_system -lboost_filesystem -lboost_timer -lboost_program_options -lboost_chrono -lc++
clang-8: warning: argument unused during compilation: '-ansi' [-Wunused-command-line-argument]
ld: library not found for -liomp5
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)

I do not know how to solve this problem.. Is there anybody can help me?

**Comment by yujitach** [comment]
Did you manage to install it? Sorry for not helping. How did you resolve the issue?

**Comment by Ha-oyzhang** [comment]
> Did you manage to install it? Sorry for not helping. How did you resolve the issue?

Thanks for your reply! 

Sadly, I didn't fix the problem but I find it's easy to install SDPB using Linux.

**Comment by yujitach** [comment]
I see. This tap is for the old SDPB1, and I need to update it to SDPB2 anyway...
